#This is Example configuration file
# IDTP Daemon Configuration

ServerName idtpd

Listen 443

BindAddress 0.0.0.0

Version 0.01

DataDirectory ./data

IndexDirectory ./data/indexes

MaxConnections 10

NonceTTL 300

Agent "WIRP IDTP Daemon 0.01"

# Security
RequireSignature yes
PacketTimeout 300
